server:
  port: 80
mybatis:
  typeAliasesPackage: com.it.demp.dao
  mapper-locations: classpath:/com/it/demo/demo/dao.*.xml
spring: 
  datasource: 
    url : jdbc:mysql://192.168.142.136:3306/keystone
    username : keystone
    password : fankaikai
    driverClassName : com.mysql.jdbc.Driver